<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Version>2.1.0</Version>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
        <FileVersion>2.1.0.0</FileVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>none</DebugType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <TempDir>$([System.IO.Path]::GetTempPath())</TempDir>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath Condition="Exists('\opt\BepInEx')">\opt\BepInEx\core\0Harmony.dll</HintPath>
            <HintPath Condition="Exists('..\libs\BepInEx')">..\libs\BepInEx\core\0Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="BepInEx">
            <HintPath Condition="Exists('\opt\BepInEx')">\opt\BepInEx\core\BepInEx.dll</HintPath>
            <HintPath Condition="Exists('..\libs\BepInEx')">..\libs\BepInEx\core\BepInEx.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="BepInEx.Harmony">
            <HintPath Condition="Exists('\opt\BepInEx')">\opt\BepInEx\core\BepInEx.Harmony.dll</HintPath>
            <HintPath Condition="Exists('..\libs\BepInEx')">..\libs\BepInEx\core\BepInEx.Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="assembly_valheim">
            <HintPath Condition="Exists('$(TempDir)assembly_valheim.public.dll')">$(TempDir)assembly_valheim.public.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\assembly_valheim.public.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath Condition="Exists('\opt\steam\libs')">\opt\steam\libs\Unity.TextMeshPro.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\Unity.TextMeshPro.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath Condition="Exists('\opt\steam\libs')">\opt\steam\libs\UnityEngine.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\UnityEngine.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath Condition="Exists('\opt\steam\libs')">\opt\steam\libs\UnityEngine.CoreModule.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath Condition="Exists('\opt\steam\libs')">\opt\steam\libs\UnityEngine.TextRenderingModule.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\UnityEngine.TextRenderingModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
	<Reference Include="UnityEngine.UI">
            <HintPath Condition="Exists('\opt\steam\libs')">\opt\steam\libs\UnityEngine.UI.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
	<Reference Include="UnityEngine.UIModule">
            <HintPath Condition="Exists('\opt\steam\libs')">\opt\steam\libs\UnityEngine.UIModule.dll</HintPath>
            <HintPath Condition="Exists('..\libs\valheim')">..\libs\valheim\UnityEngine.UIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

</Project>
